export const RESULTS_LOADED = "RESULTS_LOADED";

export const FILTERS_LOADING = "FILTERS_LOADING ";
export const FILTERS_LOADED = "FILTERS_LOADED";
export const COLUMNS_SELECTED = "COLUMNS_SELECTED";

export const FILTER_OPTIONS_SET_PAGE = "FILTER_OPTIONS_SET_PAGE";
export const FILTER_OPTIONS_SET_WHERE = "FILTER_OPTIONS_SET_WHERE";
export const FILTER_OPTIONS_SET_ORDERBY = "FILTER_OPTIONS_SET_ORDERBY";
export const FILTER_OPTIONS_SET_TAKE = "FILTER_OPTIONS_SET_TAKE";
export const FILTER_OPTIONS_SET_SKIP = "FILTER_OPTIONS_SET_SKIP";

export const AUTH_LOGIN_REQUEST = "AUTH_LOGIN_REQUEST";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const MENU_LOADED = "MENU_LOADED";
export const MENU_CLEAR = "MENU_CLEAR";

export const USERS_LOADED = "USERS_LOADED";

export const CHATS_LOADED = "CHATS_LOADED";
export const MESSAGES_LOADED = "MESSAGES_LOADED";