export const RESULTS_LOADING = "RESULTS_LOADING";
export const RESULTS_LOADED = "RESULTS_LOADED";

export const FILTERS_LOADING = "FILTERS_LOADING ";
export const FILTERS_LOADED = "FILTERS_LOADED";

export const FILTER_OPTIONS_SET_PAGE = "FILTER_OPTIONS_SET_PAGE";
export const FILTER_OPTIONS_SET_WHERE = "FILTER_OPTIONS_SET_WHERE";
export const FILTER_OPTIONS_SET_ORDERBY = "FILTER_OPTIONS_SET_ORDERBY";

